export const CREATE_MARKET = 'CREATE_MARKET';
export const HANDLE_MARKET_MODAL = 'CREATE_MARKET_MODAL';
export const ADD_MARKET_TAG = 'ADD_MARKET_TAG';
export const ADD_MARKET_NAME = 'ADD_MARKET_NAME';
export const REMOVE_MARKET_TAG = 'REMOVE_MARKET_TAG';
