export const ADD_PRODUCT = 'CREATE_PRODUCT';
export const INITAL_PRODUCT = 'INITAL_PRODUCT';
export const TAB_INDEX = 'TAB_INDEX';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
