export const ADD_PRODUCT = 'CREATE_PRODUCT';
export const INITAL_PRODUCT = 'INITAL_PRODUCT';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SHIPPED = 'EDIT_PRODUCT_SHIPPED';
export const EDIT_PRODUCT_DESCRIPTION = 'EDIT_PRODUCT_DESCRIPTION';
export const EDIT_PRODUCT_PRICE = 'EDIT_PRODUCT_PRICE';
